name: TMDC Docker Image CI workflow

on:
  push:
    tags:
      - 'v*[0-9]+.*[0-9]+.*[0-9]-d*'

jobs:
# For RELEASE STEPS

  dev-release:
    name: Release Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-d')
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        # cache-from: type=gha
        # cache-to: type=gha,mode=max
        build-args: BINGO=false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/logging-operator:${{ github.ref_name }}
    